### ISSUE TITLE
$*REPO and CompUnit::Repository::* classes not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#502]
Code:

``` perl6
say WHAT $*REPO
```

Result:

```
(Installation)
```

**Comment by jonathanstowe** [comment]
I think this wants to be done with all the other CUR stuff, note also that it not always a ```CompUnit::Repository::Installation```  : 

```
[jonathan@coriolanus doc.master]$ perl6 -Ilib -e 'say $*REPO.^name'
CompUnit::Repository::FileSystem
[jonathan@coriolanus doc.master]$ perl6  -e 'say $*REPO.^name'
CompUnit::Repository::Installation
```

**Comment by JJ** [comment]
There's not much about [compunit in the documentation](https://docs.perl6.org/language/modules#index-entry-compunit-need). Maybe create a new page?

**Comment by ugexe** [comment]
`$*REPO` is a linked list -- what it contains depends on where it is in the list. It has nothing to do with `.git` nor does it have anything to do with the directory a program is run it. At the risk of sounding harsh: nothing in the commit that closed this issue makes sense.

**Comment by JJ** [comment]
And what would make sense?

**Comment by ugexe** [comment]
Some things that would make sense:
1) revert the offending commit.
2) ask what “makes sense” before commiting work that isn’t understood.

And I hate to say it but this was part of grant related work so it looks even worse.

**Comment by niner** [comment]
JJ: please have a look at https://github.com/rakudo/rakudo/blob/master/docs/module_management.md
and http://niner.name/talks/A%20look%20behind%20the%20curtains%20-%20module%20loading%20in%20Perl%206/
"Not documented" has not been entirely accurate.

**Comment by ohmycloud** [comment]
There are two broken links in the https://docs.perl6.org/type/CompUnit::Repository::Installation page:
CompUnit::Repository and CompUnits, shows 404 when clicked.

**Comment by lizmat** [comment]
With the addition of lemmas for `CompUnit::Repository` and `CompUnit`, I think the broken links are now fixed.

**Comment by rafaelschipiura** [comment]
$*REPO and CompUnit::Repository::* have been documented, closing the bug report.

**Comment by JJ** [comment]
Most classes are still not documented; CompUnit::Repository is not either for the time being. Sorry, I'm reopening.

**Comment by JJ** [comment]
$*REPO is now documented [here](https://docs.raku.org/language/compilation#$*REPO), but the index still points to the definition in the glossary. We need either to change indexing, or to make one point to the other.

**Comment by JJ** [comment]
[This issue on how to set RAKULIB to different types of repositories will help](https://github.com/ugexe/zef#custom-installation-locations) (mentioned in https://github.com/ugexe/zef/issues/430 by @ugexe )
