### ISSUE TITLE
broken link https://docs.perl6.org/type/int on page https://docs.perl6.org/type/Int#Operators

### ISSUE THREAD

**Issue by grizzlysmit** [perl6/doc#935]
in the type graph the int bubble

**Comment by AlexDaniel** [comment]
Hmm, should be “nativeint”? Do I get it right that “int” is “nativeint” because we want it to work on case-insensitive file systems?

**Comment by gfldex** [comment]
The problem of case insensitive FS is untackled.

**Comment by JJ** [comment]
Related to #561. But not sure if still relevant.

**Comment by JJ** [comment]
This was probably temporary. It's solved now.

**Comment by rabbitisle** [comment]
I'm afraid the issue still persists. The int in the type graph still leads to a 404.

**Comment by JJ** [comment]
That's absolutely right. I don't know if it persists, or it went away and then left, but it's missing now, so we have to address it.

**Comment by JJ** [comment]
It points to https://docs.perl6.org/language/nativecall%23Passing_and_Returning_Values, which does not exist. If you substitute the %23 for a / it does not exist either.

**Comment by JJ** [comment]
This is the consequence of a RewriteRule:
    RewriteRule ^type/int(8|16|32|64)?(.html)?$ https://docs.perl6.org/language/nativecall#Passing_and_Returning_Values [R=301]

I have no idea who inserted that or why.

**Comment by JJ** [comment]
I see no other way out than actually creating the page. Won't be able to create it for every single intxx. Will have to be transformed to `/syntax/` URLs

**Comment by JJ** [comment]
Links have been been fixed since #2749, but the links from the generated graph are still 404.
